universe:
  symbols:
  - SPY
  - NVDA
  - AAPL
  - GOOG
  - MSFT
  - AMZN
  - META
  - TSLA
  - LLY
  - JPM
  - V
  - XOM
  - JNJ
  - MA
  - COST
  - ABBV
  - BAC
  - NFLX
  - HD
  - PG
  - AMD
  - PLTR
  - CVX
  - GE
  - ORCL
  - UNH
  - CSCO
  - KO
  - IBM
  - WFC
  - CAT
  - AMAT
  - LRCX
  - PM
  - MRK
  - GS
  - MU
  - RTX
  - TMO
  - MCD
  - MS
  - CRM
  - C
  - DIS
  - PEP
  - LIN
  - AXP
  - ABT
  - ISRG
  - KLAC
  - BA
  - AMGN
  - NEE
  - GEV
  - ACN
  - APH
  - INTC
  - SCHW
  - UBER
  - TJX
  - T
  - QCOM
  - VZ
  - BKNG
  - BLK
  - SPGI
  - INTU
  - GILD
  - DHR
  - TXN
  - PFE
  - ANET
  - LOW
  - BSX
  - UNP
  - COF
  - DE
  - AVGO
  - ETN
  - HON
  - WELL
  - ADBE
  - PANW
  - SYK
  - COP
  - PGR
  - MDT
  - ADI
  - PLD
  - PH
  - VRTX
  - BX
  - CRWD
  - CB
  - LMT
  - CMCSA
  - ADP
  - MCK
  - CVS
  - BMY
  - TMUS
  - SBUX
  - MO
  - SO
  - CME
  - NEM
  - GD
  - DUK
  - CEG
  - MMC
  - WM
  - MCO
  - SNPS
  - CDNS
  - MMM
  - USB
  - ICE
  - TT
  - AMT
  - KKR
  - BK
  - NOC
  - ORLY
  - UPS
  - SHW
  - TDG
  - EQIX
  - DASH
  - EMR
  - ECL
  - NKE
  - ELV
  - MAR
  - REGN
  - MDLZ
  - RCL
  - WDC
  - WMB
  - HCA
  - GLW
  - CI
  - PNC
  - CMI
  - AON
  - JCI
  - FCX
  - HLT
  - ITW
  - WBD
  - GM
  - FDX
  - PWR
  - CTAS
  - CSX
  - TEL
  - COR
  - RSG
  - AJG
  - NSC
  - TFC
  - CL
  - APO
  - AEP
  - PCAR
  - MSI
  - TRV
  - SPG
  - ROST
  - EOG
  - NXPI
  - URI
  - APD
  - BDX
  - KMI
  - SLB
  - MNST
  - ADSK
  - AZO
  - SRE
  - AFL
  - PSX
  - IDXX
  - ZTS
  - VLO
  - ABNB
  - O
  - PYPL
  - MPC
  - F
  - STX
  - LHX
  - DLR
  - FTNT
  - D
  - VST
  - ALL
  - DFS
  - NDAQ
  - TGT
  - BKR
  - EW
sector_map:
  source: csv
  path: data/raw/sector_map.csv
prices:
  source: yfinance
  start: '2023-01-01'
  end: '2026-01-28'
  max_missing_pct: 0.2
